### ISSUE TITLE
broken pls fix

### ISSUE THREAD

**Issue by brkastner** [evansendra/redux-todo#1]
hey ur app is broken pls fix

**Comment by evansendra** [comment]
#2advanced4u

**Comment by brkastner** [comment]
fyi hashtags don't work on github guy

**Comment by evansendra** [comment]
Damn bro no way!  I totally wanted to reference all the other "2advanced4u" comments out there...Thank God 4 u BK

**Comment by brkastner** [comment]
I go by K,B now

**Comment by evansendra** [comment]
Doesn't hold up, chief.

![capture](https://cloud.githubusercontent.com/assets/3901321/23470200/18e23880-fea6-11e6-8421-94e70afb8a08.JPG)

**Comment by brkastner** [comment]
false 
![2017-03-01--1488386618_302x325_scrot](https://cloud.githubusercontent.com/assets/880291/23470433/fb2fd17e-fe6b-11e6-886c-f0bb5ecbba7c.png)

**Comment by evansendra** [comment]
lmao you actually changed it 😂

**Comment by brkastner** [comment]
yeah weeks ago I told you I go by k,b now idk why you had a screenshot of my old name that's weird

**Comment by evansendra** [comment]
How could you have told me? I live in Europe now, k,b. Get real.

**Comment by brkastner** [comment]
![2017-03-01--1488387472_373x118_scrot](https://cloud.githubusercontent.com/assets/880291/23471136/eef4fa7c-fe6d-11e6-97dc-77e7c38101b7.png)

**Comment by brkastner** [comment]
when u coming back to the greatest country in the world to visit?
